POST https://node-videos.onrender.com/videos
content-type: application/json

{
    "title": "video node",
     "description": "essse é o video 01",
     "duration": 180
}

###

GET https://node-videos.onrender.com/videos

###

PUT https://node-videos.onrender.com/videos/4d6aaabd-03ed-4b2e-839d-af07f1519b47
content-type: application/json

{
    "title": "video 03",
     "description": "essse é o video 01",
     "duration": 180
}

###
DELETE https://node-videos.onrender.com/videos/4d6aaabd-03ed-4b2e-839d-af07f1519b47